import React from 'react';
import type { SubtitleTrack, AudioTrack } from '../../../api';

export interface VideoPlayerViewProps {
  videoRef: React.RefObject<HTMLVideoElement | null>;
  containerRef: React.RefObject<HTMLDivElement | null>;
  profileId: string;
  profileToken: string;
  isPlaying: boolean;
  setIsPlaying: (playing: boolean) => void;
  duration: number;
  currentTime: number;
  bufferedTime: number;
  volume: number;
  isMuted: boolean;
  isLoading: boolean;
  setIsLoading: (loading: boolean) => void;
  playbackSpeed: number;
  showControls: boolean;
  isFullscreen: boolean;
  isEnded: boolean;
  currentVideoPath: string;
  playlist: string[];
  subtitles: SubtitleTrack[];
  audioTracks: AudioTrack[];
  activeSubtitle: number | null;
  activeAudio: number | null;
  subtitleAnchor: HTMLElement | null;
  setSubtitleAnchor: (el: HTMLElement | null) => void;
  audioAnchor: HTMLElement | null;
  setAudioAnchor: (el: HTMLElement | null) => void;
  speedAnchor: HTMLElement | null;
  setSpeedAnchor: (el: HTMLElement | null) => void;
  handleTimeUpdate: () => void;
  handleProgress: () => void;
  handleLoadedMetadata: () => void;
  handlePlayPause: () => void;
  handleVideoEnded: () => void;
  handleReplay: () => void;
  handleSeeking: () => void;
  handleSeeked: () => void;
  handleWaiting: () => void;
  handlePlaying: () => void;
  hasPrevious: boolean;
  hasNext: boolean;
  playPrevious: () => void;
  playNext: () => void;
  cycleAudio: () => void;
  handleSeek: (e: any, value: number | number[]) => void;
  seekRelative: (seconds: number) => void;
  handleVolumeChange: (e: any, value: number | number[]) => void;
  toggleMute: () => void;
  adjustVolume: (delta: number) => void;
  toggleFullscreen: () => void;
  handleSpeedSelect: (speed: number) => void;
  selectSubtitle: (trackIndex: number | null) => void;
  cycleSubtitles: () => void;
  selectAudioTrack: (trackIndex: number | null) => void;
  togglePictureInPicture: () => void;
  formatTime: (secs: number) => string;
  onClose: () => void;
}
